### ISSUE TITLE
Provide the ability to reconnect (in the case of reauthentication)

### ISSUE THREAD

**Issue by brendon** [mclintprojects/actioncable-vue#16]
**Is your feature request related to a problem? Please describe.**
Currently I can't see a way to ask the connection to close and then reopen a new connection (using a potentially updated cookie) in the case that ActionCable was connected before a user logged in and needs to be reconnected to take into account a users credentials once they log in.

**Describe the solution you'd like**
Exposing the connection object in some way would allow one to close and open the connection as necessary. Care would have to be taken around subscriptions though.

**Describe alternatives you've considered**
Currently I don't connect automatically and ensure any components that have subscriptions aren't shown if the user is logged out. This prevents a connection but is brittle if I forget about this requirement and make a future component visible while logged out. It could also be a feature to have a logged out component needing access to the cable.

**Comment by mclintprojects** [comment]
> Care would have to be taken around subscriptions though.
Can you please elaborate further what you mean by this?

Also, what would you like to have in the exposed connection object?

**Comment by brendon** [comment]
Hi @mclintprojects, regarding subscriptions, I'm not sure if they'd re-subscribe upon reconnect. I assume they probably would since that is what happens when the network goes away and comes back.

For a connection object, the ability to close, open, and reopen. It'd just basically be exposing the connection from `action_cable`: https://github.com/rails/rails/blob/master/actioncable/app/javascript/action_cable/connection.js

Perhaps as a global? `this.$actioncableconnection`?! That's a horrible name :D

**Comment by mclintprojects** [comment]
Hi @brendon! I just pushed a new [build](https://github.com/mclintprojects/actioncable-vue/blob/mc/expose-connection/dist/actioncablevue.js) to the repository. Kindly test that the `disconnect` and `connect` methods available on `this.$cable.connection` work as expected. Also, check if re-connection automatically happens for existing subscriptions and if not I'll add code to manually do it.

**Comment by brendon** [comment]
Hi @mclintprojects, thank you so much for working on this.

I'm getting an error:

```
vue.runtime.esm.js:638 [Vue warn]: Error in v-on handler: "TypeError: Cannot read property 'disconnect' of undefined"

at Object.disconnect (actioncablevue.js:527)
```

It seems like this._cable isn't set there?

**Comment by mclintprojects** [comment]
You need to have connected at least once before `this. _cable` will be defined. To connect just create a subscription or do not set `connectImmediately` during setup to false.

Is that an incorrect implementation?

**Comment by brendon** [comment]
By default I have `connectImmediately` as false but I tried removing that and still get the same trouble. I have an active cable connection running on the page and a couple of subscriptions too. Very strange. Let me know what else you want me to look into :)

**Comment by brendon** [comment]
I'm no js-pro but is `this` bound correctly here?:

```
   if (this._cable) this._attachConnectionObject();
  }

  _attachConnectionObject() {
    this.connection = {
      connect() {
        this._cable.connect();
      },
      disconnect() {
        this._cable.disconnect();
      },
    };
  }
```

**Comment by mclintprojects** [comment]
Yes. It seems to be. I wrote tests to check for that. I've pushed a new [build](https://github.com/mclintprojects/actioncable-vue/blob/mc/expose-connection/dist/actioncablevue.js). Please try that too.

**Comment by brendon** [comment]
Certainly a strange one. I've tried your new commit on the branch and am getting `TypeError: this._connect is not a function` on calling connect.

via this:
```
this._cable ? this._cable.connect() : this._connect(t || this._connectionUrl);
```

`disconnect()` does nothing and raises nothing, but that's just because of the missing `_cable` object. The actual web socket continues to be open and pinging.

Hope that helps :)

**Comment by mclintprojects** [comment]
Ahh. Now I know the context was not properly bound. I think I've fixed it now. Please try the latest [build](https://github.com/mclintprojects/actioncable-vue/blob/mc/expose-connection/dist/actioncablevue.js)

**Comment by brendon** [comment]
That works perfectly! :) It reconnects and resubscribes too the appropriate channels also.

You just have to remove the `console.log()`

I'm also not sure you'll need the guards you added: `if (this._cable)`. Perhaps you need the one that connects for the first time in the case of auto connect being false? Hard to say.

**Comment by mclintprojects** [comment]
Yeah. I think the guards are needed especially for connect. It's possible that someone might set `connectImmediately` to false during setup. For disconnect, maybe not that necessary but better to be safe in case someone does not connect before attempting to disconnect.

I'll update the README and publish a new version to NPM today. Thank you for your help.

**Comment by brendon** [comment]
Thanks @mclintprojects. This is the best open source interaction I've had in a long time :D
